### ISSUE TITLE
[PE-D][Tester E] Filter Buyers description does not match its entry in the Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-1/tp#160]
Inside the Command Summary, the `-fuzzy` keyword is present in the example

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/6659c30d-b6f3-4aee-a392-7574ab817d98.png)

However, inside the command's description, the usage or purpose of `-fuzzy` is not mentioned.

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/a12c651f-a502-465f-8923-700018ca7fbf.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wrewsama/ped#2

**Comment by chngchngchng** [comment]
Fixed
