### ISSUE TITLE
[PE-D][Tester E] Overzealous input validation of `name` for `addbuyer`

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-1/tp#167]
Command executed: `addbuyer -n Ninomae Ina'nis -ph 12345678 -e inachan@holomyth.com -a holomyth`.

Expected: buyer named "Ninomae Ina'nis" to be added.

Actual outcome: command was blocked.

Screenshot:

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/961cc3e3-5c6a-4a0d-9288-56c5d6715547.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wrewsama/ped#6

**Comment by ChryslineLim** [comment]
change name criteria if have time
