### ISSUE TITLE
[PE-D][Tester A] UG: non-working example command for filterbuyer

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-1/tp#176]
This command given in the UG does not work:

![image.png](https://raw.githubusercontent.com/Piyotato/ped/main/files/b6f67d32-21cb-42cf-9f47-5572305d99b3.png)

It gives the following output:

![image.png](https://raw.githubusercontent.com/Piyotato/ped/main/files/8c0cd525-a46f-482b-8b15-e1d0fa61abae.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Piyotato/ped#7

**Comment by chngchngchng** [comment]
Fixed documentation bug
