### ISSUE TITLE
[PE-D][Tester E] The `filterbuyers` command does not work even with the example input given in the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-1/tp#185]
Command executed: `filterbuyers -p 500000 -c bright; sunny -priority HIGH` (taken from the command summary section)

Expected: command to execute and buyers list to be filtered.

Actual: Error message shown, command not executed

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/d69c70e7-5011-4597-8fa6-e4973cd2be5a.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: wrewsama/ped#9

**Comment by ChryslineLim** [comment]
edit UG w syntax

**Comment by chngchngchng** [comment]
Fixed UG documentation error
