### ISSUE TITLE
[PE-D][Tester E] Optionality of `-fuzzy` and `-strict` unclear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-1/tp#192]
The keywords `-fuzzy` and `-strict` appear in the examples without any square brackets, suggesting that they are not optional. However, the commands still work without including them.

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/ed1cedfc-7895-410c-9a19-411d4b191448.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wrewsama/ped#11

**Comment by ChryslineLim** [comment]
standardize format across error msgs and UG
compulsory: nth
optional: [ ]
Specify in UG that tags can be in any order except if it's an index; must follow immediately aft the command
