### ISSUE TITLE
[PE-D][Tester D] Swopped editprop and editbuyer sequence.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-1/tp#197]
![image.png](https://raw.githubusercontent.com/kynapy/ped/main/files/54c4bc89-0d5f-4549-b8eb-a08f7d19d94a.png)
Maybe it's my OCD but the UG has the sequence of buyer then prop first for all commands except edit

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kynapy/ped#5

**Comment by chngchngchng** [comment]
Rearranged order of commands
