### ISSUE TITLE
[PE-D][Tester E] Misleading description in UG for `help`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-1/tp#207]
The UG mentions that a list of commands and related syntax will appear, however, the help page only opens this popup:

![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/7f8f006c-85b2-4278-b619-6725b5da4794.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wrewsama/ped#16

**Comment by chngchngchng** [comment]
Fixed description
