### ISSUE TITLE
As a property agent with many clients, I want to avoid duplicate contacts, so I can have a neat list of clients to contact

### ISSUE THREAD

**Issue by ChryslineLim** [AY2223S1-CS2103T-F12-1/tp#21]

**Comment by zsiggg** [comment]
v1.2 achieves this by preventing same name buyers, and same name + price properties.

Consider:
1. Allowing same name buyer?
2. Changing the criteria for duplicate property? (doesn't seem to make much sense that same name and price properties are not allowed, but same name+address and diff price properties is not allowed)
