### ISSUE TITLE
[PE-D][Tester E] Unnecessary capitalisation in FAQ question 1

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-1/tp#210]
![image.png](https://raw.githubusercontent.com/wrewsama/ped/main/files/a6d5c850-ff33-4956-8255-5abf1648b72e.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wrewsama/ped#19

**Comment by chngchngchng** [comment]
Removed unnecessary capitalisation
